#docs at https://docs.spring.io/spring-boot/docs/3.2.1/reference/htmlsingle/#howto.webserver
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://192.168.129.30:5432/postgres
    username: postgres
    password: choho123
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  main:
    web-application-type: servlet